baseURL = 'https://joachimkennedy.com/'
languageCode = 'en-us'
title = 'Joachim Kennedy'
author = 'Joachim Kennedy'
theme = 'contrast-hugo'

[params]
    minimal = true
    description = 'my blog'

[menu]
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/p/"
    weight = 10
[[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = "10"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

