baseURL = 'https://joachimkennedy.com/'
languageCode = 'en-us'
title = 'Joachim Kennedy'
author = 'Joachim Kennedy'
theme = 'contrast-hugo'

[params]
    minimal = true
    description = 'my blog'
    excerpts = true

[menu]
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/p/"
    weight = 2
[[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 3
[[menu.main]]
    identifier = "directory"
    name = "Directory"
    url = "/directory/"
    weight = "10"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

