baseURL = 'https://joachimkennedy.com/'
locale = 'en-us'
title = 'Joachim Kennedy'
author = 'Joachim Kennedy'
theme = 'ugly'

[params]
    minimal = true
    description = 'my blog'
    excerpts = true

[menu]
[[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = "1"
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/p/"
    weight = 2
[[menu.main]]
    identifier = "directory"
    name = "Directory"
    url = "/directory/"
    weight = "10"
[[menu.main]]
    identifier = "bookmarks"
    name = "Bookmarks"
    url = "/bookmarks/"
    weight = "20"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

