baseURL = 'https://joachimkennedy.com/'
languageCode = 'en-us'
title = 'Joachim Kennedy'
author = 'Joachim Kennedy'
theme = 'contrast'

[params]
    minimal = true
    description = 'my blog'
    excerpts = true

[menu]
[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/p/"
    weight = 2
[[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 3
[[menu.main]]
    identifier = "directory"
    name = "Directory"
    url = "/directory/"
    weight = "10"
[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = "15"
[[menu.main]]
    identifier = "rss"
    name = "rss"
    url = "/p/index.xml"
    weight = "20"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

