# This is a basic workflow that is triggered on git push

name: Deploy site

# Controls when the action will run.
on: push

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Generate pages
      run: hugo --cleanDestinationDir --minify
    - name: Upload to server
      run: rsync -avz --delete public/ root@www.joachimkennedy.com:/var/www/blog
